# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.3.0"
dependencies:
    - OpenZeppelin/openzeppelin-contracts@3.3.0